[book]
authors = ["assari-harassment"] # あなたのリポジトリ名または名前
language = "en"
title = "ボイスメモアプリのシステムドキュメント" # 適切なタイトルを設定

[output.html]
additional-js = ["./mermaid-init.js"]

[preprocessor.plantuml]
plantuml-cmd = "https://www.plantuml.com/plantuml"
