[book]
authors = []
language = "en"

[output.html]
additional-head-content = '<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script><script>document.addEventListener("DOMContentLoaded", function() { mermaid.initialize({ startOnLoad: true }); });</script>'