site_name: My Docs
use_directory_urls: false
site_url: https://assari-harassment.github.io/voicebooklm-docs/
repo_url: https://github.com/assari-harassment/voicebooklm-docs
theme:
  name: material
  features:
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
nav:
  - Home: index.md
  - Activity Diagram: Voicememo-activity.md
  - Use Case Diagram: voicememo-usecase.md
